### ISSUE TITLE
OSX Install

### ISSUE THREAD

**Issue by ethanmcc** [akehrer/fiddle#1]
Hi. I'm interested in checking this out but am having trouble building. I've installed several system packages:

    brew install qt
    brew install sip --with-python3
    brew install pyqt --with-python3
    brew install qscintilla2 --with-python3

And pip requirements:

    pip3 install cx_freeze
    pip3 install chardet
    pip3 install autopep8
    pip3 install pyflakes

When I run `python3 setup.py build`, I get a cx_Freeze error:

    cx_Freeze.freezer.ConfigError: cannot find file/directory named locale

I see this is in early development, so no rush or obligation, but I'd love to give it a whirl if you have ideas on what might help get this running.

**Comment by akehrer** [comment]
Hi. Thanks for checking it out.
The problem is cx_freeze is looking for a `locale/` in the `include_files` options that isn't there because it's currently empty.

I've updated the master branch to include the directory and improved some of the parameters in `setup.py` for building OS X executables.

Of course doing all this helped me find another issue... #2

**Comment by ethanmcc** [comment]
thanks! working now.
